plugins {
    id 'com.android.application'
}

def releaseKeystorePath = System.getenv('ANDROID_KEYSTORE_PATH')
def releaseStorePassword = System.getenv('ANDROID_KEYSTORE_PASSWORD')
def releaseKeyPassword = System.getenv('ANDROID_KEY_PASSWORD')

android {
    namespace 'cz.goldensnack.productionterminal'
    compileSdk 35

    defaultConfig {
        applicationId 'cz.goldensnack.productionterminal'
        minSdk 21
        targetSdk 35
        versionCode 4
        versionName '1.0.3'
    }

    signingConfigs {
        release {
            if (releaseKeystorePath && releaseStorePassword && releaseKeyPassword) {
                storeFile file(releaseKeystorePath)
                storePassword releaseStorePassword
                keyAlias 'goldensnack-terminal'
                keyPassword releaseKeyPassword
            }
        }
    }

    buildTypes {
        release {
            signingConfig signingConfigs.release
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
}
